"use strict";
exports.PAY_TYPE_CREDIT = "0";
exports.PAY_TYPE_SUICA = "1";
exports.PAY_TYPE_EDY = "2";
exports.PAY_TYPE_CVS = "3";
exports.METHOD_LUMP = "1";
exports.METHOD_INSTALLMENT = "2";
exports.METHOD_BONUS_LUMP = "3";
exports.METHOD_REVOLVING = "4";
exports.METHOD_BONUS_INSTALLMENT = "5";
exports.STATUS_CVS_UNPROCESSED = "UNPROCESSED";
exports.STATUS_CVS_REQSUCCESS = "REQSUCCESS";
exports.STATUS_CVS_PAYSUCCESS = "PAYSUCCESS";
exports.STATUS_CVS_PAYFAIL = "PAYFAIL";
exports.STATUS_CVS_EXPIRED = "EXPIRED";
exports.STATUS_CVS_CANCEL = "CANCEL";
exports.STATUS_CREDIT_UNPROCESSED = "UNPROCESSED";
exports.STATUS_CREDIT_AUTHENTICATED = "AUTHENTICATED";
exports.STATUS_CREDIT_CHECK = "CHECK";
exports.STATUS_CREDIT_CAPTURE = "CAPTURE";
exports.STATUS_CREDIT_AUTH = "AUTH";
exports.STATUS_CREDIT_SALES = "SALES";
exports.STATUS_CREDIT_VOID = "VOID";
exports.STATUS_CREDIT_RETURN = "RETURN";
exports.STATUS_CREDIT_RETURNX = "RETURNX";
exports.STATUS_CREDIT_SAUTH = "SAUTH";
exports.JOB_CD_CHECK = "CHECK";
exports.JOB_CD_CAPTURE = "CAPTURE";
exports.JOB_CD_AUTH = "AUTH";
exports.JOB_CD_SALES = "SALES";
exports.JOB_CD_VOID = "VOID";
exports.JOB_CD_RETURN = "RETURN";
exports.JOB_CD_RETURNX = "RETURNX";
exports.JOB_CD_SAUTH = "SAUTH";
function createShopPassString(args) {
    let crypto = require("crypto");
    let md5hash = crypto.createHash("md5");
    md5hash.update(`${args.shop_id}${args.order_id}${args.amount.toString()}${args.shop_pass}${args.date_time}`, "utf8");
    return md5hash.digest("hex");
}
exports.createShopPassString = createShopPassString;
