export declare var PAY_TYPE_CREDIT: string;
export declare var PAY_TYPE_SUICA: string;
export declare var PAY_TYPE_EDY: string;
export declare var PAY_TYPE_CVS: string;
export declare var STATUS_CVS_UNPROCESSED: string;
export declare var STATUS_CVS_REQSUCCESS: string;
export declare var STATUS_CVS_PAYSUCCESS: string;
export declare var STATUS_CVS_PAYFAIL: string;
export declare var STATUS_CVS_EXPIRED: string;
export declare var STATUS_CVS_CANCEL: string;
export declare var STATUS_CREDIT_UNPROCESSED: string;
export declare var STATUS_CREDIT_AUTHENTICATED: string;
export declare var STATUS_CREDIT_CHECK: string;
export declare var STATUS_CREDIT_CAPTURE: string;
export declare var STATUS_CREDIT_AUTH: string;
export declare var STATUS_CREDIT_SALES: string;
export declare var STATUS_CREDIT_VOID: string;
export declare var STATUS_CREDIT_RETURN: string;
export declare var STATUS_CREDIT_RETURNX: string;
export declare var STATUS_CREDIT_SAUTH: string;
export declare var JOB_CD_CHECK: string;
export declare var JOB_CD_CAPTURE: string;
export declare var JOB_CD_AUTH: string;
export declare var JOB_CD_SALES: string;
export declare var JOB_CD_VOID: string;
export declare var JOB_CD_RETURN: string;
export declare var JOB_CD_RETURNX: string;
export declare var JOB_CD_SAUTH: string;
export declare function createShopPassString(args: {
    order_id: string;
    amount: number;
    date_time: string;
}): any;
