export declare const PAY_TYPE_CREDIT = "0";
export declare const PAY_TYPE_SUICA = "1";
export declare const PAY_TYPE_EDY = "2";
export declare const PAY_TYPE_CVS = "3";
export declare const METHOD_LUMP = "1";
export declare const METHOD_INSTALLMENT = "2";
export declare const METHOD_BONUS_LUMP = "3";
export declare const METHOD_REVOLVING = "4";
export declare const METHOD_BONUS_INSTALLMENT = "5";
export declare const STATUS_CVS_UNPROCESSED = "UNPROCESSED";
export declare const STATUS_CVS_REQSUCCESS = "REQSUCCESS";
export declare const STATUS_CVS_PAYSUCCESS = "PAYSUCCESS";
export declare const STATUS_CVS_PAYFAIL = "PAYFAIL";
export declare const STATUS_CVS_EXPIRED = "EXPIRED";
export declare const STATUS_CVS_CANCEL = "CANCEL";
export declare const STATUS_CREDIT_UNPROCESSED = "UNPROCESSED";
export declare const STATUS_CREDIT_AUTHENTICATED = "AUTHENTICATED";
export declare const STATUS_CREDIT_CHECK = "CHECK";
export declare const STATUS_CREDIT_CAPTURE = "CAPTURE";
export declare const STATUS_CREDIT_AUTH = "AUTH";
export declare const STATUS_CREDIT_SALES = "SALES";
export declare const STATUS_CREDIT_VOID = "VOID";
export declare const STATUS_CREDIT_RETURN = "RETURN";
export declare const STATUS_CREDIT_RETURNX = "RETURNX";
export declare const STATUS_CREDIT_SAUTH = "SAUTH";
export declare const JOB_CD_CHECK = "CHECK";
export declare const JOB_CD_CAPTURE = "CAPTURE";
export declare const JOB_CD_AUTH = "AUTH";
export declare const JOB_CD_SALES = "SALES";
export declare const JOB_CD_VOID = "VOID";
export declare const JOB_CD_RETURN = "RETURN";
export declare const JOB_CD_RETURNX = "RETURNX";
export declare const JOB_CD_SAUTH = "SAUTH";
export declare function createShopPassString(args: {
    shop_id: string;
    shop_pass: string;
    order_id: string;
    amount: number;
    date_time: string;
}): any;
